# Site settings
title: Genomic Medicine Lab
email: team@genomicmedlab.org
github: genomicmedlab
description: > # "The Wagner Lab at Nationwide Children's Hospital"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

category-list: [software, blog]

# Build settings
# theme: minima
plugins:
  - jekyll-feed

collections:
  people:
    output: true
    sort_by: role
  papers:
    output: true
  projects:
    output: true
  software:
    output: true
